# Generated by Django 5.1.3 on 2024-11-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecrivain',
            fields=[
                ('ecrivain_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('num_tlphn', models.CharField(blank=True, max_length=15, null=True)),
                ('nationalite', models.CharField(max_length=50)),
                ('cv', models.ImageField(upload_to='cv/')),
                ('certificats', models.ImageField(upload_to='certificats/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('medical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ecrit',
            fields=[
                ('ecrit_id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('article', 'Article'), ('these', 'Thèse')], max_length=10)),
                ('description', models.TextField()),
                ('contenu', models.TextField()),
                ('ecrivain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.ecrivain')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('ecrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.ecrit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('favorit_id', models.AutoField(primary_key=True, serialize=False)),
                ('ecrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.ecrit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.user')),
            ],
            options={
                'unique_together': {('ecrit', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.ecrit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmedapp.user')),
            ],
            options={
                'unique_together': {('ecrit', 'user')},
            },
        ),
    ]
