# Generated by Django 5.0 on 2024-12-27 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecrit',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
