# Generated by Django 5.1.3 on 2024-12-23 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecrit',
            name='date_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
