# Generated by Django 5.1.3 on 2024-12-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmedapp', '0002_ecrit_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecrivain',
            old_name='ecrivain_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
